/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#13b6ec",
        "primary-dark": "#0a9acb",
        "primary-hover": "#0ea4d6",
        "secondary": "#fbbf24",
        "background-light": "#fcfcfc",
        "background-dark": "#101d22",
        "surface-dark": "#0d181b",
        "ink": "#111111",
        "near-black": "#0d181b",
        "off-white": "#f8fbfc",
        "surface": "#ffffff",
        "paper": "#F4F3EF",
        "accent-yellow": "#ffd700",
        "accent-red": "#ff4d4d",
        "accent-orange": "#ff9900",
        "accent-blue": "#3b82f6",
        "border-dark": "#111111",
        "neutral-black": "#111111",
        "status-red": "#ef4444",
        "status-green": "#22c55e",
        "danger": "#e74c3c",
        "dark": "#1a1a1a",
        "light": "#f8f9fa",
        "light": "#f8f9fa",
      },
      fontFamily: {
        "sans": ["IBM Plex Sans", "sans-serif"],
        "mono": ["IBM Plex Mono", "monospace"],
        "display": ["Space Grotesk", "sans-serif"],
        "body": ["Space Grotesk", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0px",
        "sm": "2px",
        "md": "4px",
        "lg": "6px",
        "xl": "6px",
        "full": "9999px"
      },
      boxShadow: {
        "hard": "6px 6px 0 0 #1a1a1a",
        "hard-sm": "3px 3px 0 0 #1a1a1a",
        "hard-hover": "2px 2px 0 0 #1a1a1a",
        "neo": "6px 6px 0px 0px #111111",
        "neo-sm": "3px 3px 0px 0px #111111",
        "neo-hover": "2px 2px 0px 0px #111111",
        "neo-active": "2px 2px 0px 0px #111111",
        "brutal": "6px 6px 0px 0px #111111",
        "brutal-sm": "3px 3px 0px 0px #111111",
        "brutal-hover": "2px 2px 0px 0px #111111",
        "neobrutalism": "6px 6px 0px 0px #1a1a1a",
        "neobrutalism-sm": "3px 3px 0px 0px #1a1a1a",
        "neobrutalism-hover": "2px 2px 0px 0px #1a1a1a",
      },
      borderWidth: {
        "3": "3px",
      }
    },
  },
  plugins: [],
}