/** Dashboard overview catalog tiles — static config only. */

export const EXPLORE_LINKS = [
  {
    href: '/deals',
    icon: 'local_offer',
    label: 'All Deals',
    sub: 'Cloud, SaaS & ad credits',
    iconClass: 'text-sky-500 dark:text-sky-400',
    plateClass: 'bg-sky-500/10 border-sky-500/25 group-hover:bg-sky-500/15',
    glowClass: 'group-hover:bg-sky-500/15',
    hoverBorder: 'hover:border-sky-500/35',
  },
  {
    href: '/flash-deals',
    icon: 'bolt',
    label: 'Flash Deals',
    sub: 'Limited-time drops',
    iconClass: 'text-amber-600 dark:text-accent-yellow',
    plateClass: 'bg-accent-yellow/10 border-accent-yellow/25 group-hover:bg-accent-yellow/15',
    glowClass: 'group-hover:bg-accent-yellow/12',
    hoverBorder: 'hover:border-accent-yellow/40',
  },
  {
    href: '/programs?type=grants',
    icon: 'payments',
    label: 'Grants',
    sub: 'Non-dilutive funding',
    iconClass: 'text-violet-500 dark:text-violet-400',
    plateClass: 'bg-violet-500/10 border-violet-500/25 group-hover:bg-violet-500/15',
    glowClass: 'group-hover:bg-violet-500/15',
    hoverBorder: 'hover:border-violet-500/35',
  },
  {
    href: '/programs?type=accelerators',
    icon: 'rocket_launch',
    label: 'Accelerators',
    sub: 'Top global programs',
    iconClass: 'text-orange-500 dark:text-orange-400',
    plateClass: 'bg-orange-500/10 border-orange-500/25 group-hover:bg-orange-500/15',
    glowClass: 'group-hover:bg-orange-500/15',
    hoverBorder: 'hover:border-orange-500/35',
  },
  {
    href: '/student-benefits',
    icon: 'school',
    label: 'Student Benefits',
    sub: 'Credits, tools & funding',
    iconClass: 'text-emerald-600 dark:text-emerald-400',
    plateClass: 'bg-emerald-500/10 border-emerald-500/25 group-hover:bg-emerald-500/15',
    glowClass: 'group-hover:bg-emerald-500/15',
    hoverBorder: 'hover:border-emerald-500/35',
  },
  {
    href: '/ideas',
    icon: 'lightbulb',
    label: 'Startup Ideas',
    sub: 'Validated opportunities',
    iconClass: 'text-fuchsia-500 dark:text-fuchsia-400',
    plateClass: 'bg-fuchsia-500/10 border-fuchsia-500/25 group-hover:bg-fuchsia-500/15',
    glowClass: 'group-hover:bg-fuchsia-500/15',
    hoverBorder: 'hover:border-fuchsia-500/35',
  },
  {
    href: '/resources',
    icon: 'lock',
    label: 'Founder Vault',
    sub: 'Guides & playbooks',
    iconClass: 'text-amber-700 dark:text-amber-400',
    plateClass: 'bg-amber-600/10 border-amber-600/25 group-hover:bg-amber-600/15',
    glowClass: 'group-hover:bg-amber-500/12',
    hoverBorder: 'hover:border-amber-500/35',
  },
  {
    href: '/deals?category=saas-discounts',
    icon: 'apps',
    label: 'SaaS Stack',
    sub: 'Tools at founder rates',
    iconClass: 'text-indigo-500 dark:text-indigo-400',
    plateClass: 'bg-indigo-500/10 border-indigo-500/25 group-hover:bg-indigo-500/15',
    glowClass: 'group-hover:bg-indigo-500/15',
    hoverBorder: 'hover:border-indigo-500/35',
  },
  {
    href: '/submit-deal',
    icon: 'add_circle',
    label: 'Submit Deal',
    sub: 'Share with founders',
    iconClass: 'text-rose-500 dark:text-rose-400',
    plateClass: 'bg-rose-500/10 border-rose-500/25 group-hover:bg-rose-500/15',
    glowClass: 'group-hover:bg-rose-500/15',
    hoverBorder: 'hover:border-rose-500/35',
  },
] as const